// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  tutorialSidebar: [
    {
      type: "category",
      label: "Business",
      items: [
        {
          type: "autogenerated",
          dirName: "business",
        },
      ],
    },
  ],

  cybersecuritySidebar: [
    {
      type: "category",
      label: "CyberSecurity",
      items: [
        {
          type: "autogenerated",
          dirName: "cybersecurity",
        },
      ],
    },
  ],

  educationSidebar: [
    {
      type: "category",
      label: "Education",
      items: [
        {
          type: "autogenerated",
          dirName: "education",
        },
      ],
    },
  ],

  // servicesSidebar: [
  //   {
  //     type: "category",
  //     label: "Services",
  //     items: [
  //       {
  //         type: "autogenerated",
  //         dirName: "services",
  //       },
  //     ],
  //   },
  // ],

  servicesSidebar: [
    {
      type: "autogenerated",
      dirName: "services",
    },
  ],

  // But you can create a sidebar manually

  // tutorialSidebar: [
  //   'intro',
  //   'hello',
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['tutorial-basics/create-a-document'],
  //   },
  // ],
};

export default sidebars;
